Repository crate/crate-operator, pull requests merged in 2020-11, with the labels that each got.

#93 Close the K8s API client's connections
  CHANGES.rst
  crate/operator/bootstrap.py
  crate/operator/main.py
  crate/operator/operations.py
  crate/operator/scale.py
  crate/operator/upgrade.py
  crate/operator/utils/kubeapi.py
  tests/conftest.py
  tests/test_backup.py
  tests/test_bootstrap.py
  tests/test_create.py
  tests/test_kubeapi.py
  tests/test_operations.py
  tests/test_scale.py
Labels: ready-to-merge

#94 Support zone awareness on Azure
  CHANGES.rst
  crate/operator/create.py
  docs/source/configuration.rst
  tests/test_create.py
Labels: ready-to-merge

#95 On Azure, pass the failure/fault domain to CrateDB nodes as `zone`
  CHANGES.rst
  crate/operator/create.py
  tests/test_create.py
Labels: ready-to-merge

#96 Set watch request timeouts
  CHANGES.rst
  crate/operator/main.py
Labels: ready-to-merge

#97 Prepare release 1.0b4
  CHANGES.rst
Labels: ready-to-merge

#104 Fix #60: Update image of mkdir-heapdump init container on upgrade
  CHANGES.rst
  crate/operator/upgrade.py
Labels: ready-to-merge

#103 Fix #84: Adjust parsing of replicas to use lower bounds
  CHANGES.rst
  crate/operator/scale.py
  tests/test_scale.py
Labels: ready-to-merge

#102 Fix #101: Rename process, diff storage, and finalizer
  CHANGES.rst
  crate/operator/main.py
  crate/operator/utils/kopf.py
Labels: ready-to-merge

#110 Make README more appealing
  README.rst
  deploy/crd.yaml
  deploy/deployment.yaml
  deploy/rbac.yaml
  docs/source/development.rst
  docs/source/installation.rst
Labels: documentation

#113 Update docs and readme
  README.rst
  docs/source/development.rst
Labels: ready-to-merge

#116 Preserve keys in annotations, labels, and settings
  CHANGES.rst
  deploy/crd.yaml
  tests/test_create.py
Labels: bug, ready-to-merge

#118 Update testing docs
  docs/source/development.rst
Labels: ready-to-merge

#119 Use zone attribute instead of fault domain on Azure
  CHANGES.rst
  crate/operator/create.py
  tests/test_create.py
Labels: ready-to-merge

#122 Bump test utilities in pre-commit
  .pre-commit-config.yaml
  crate/operator/backup.py
  crate/operator/bootstrap.py
  crate/operator/cratedb.py
  crate/operator/create.py
  crate/operator/kube_auth.py
  crate/operator/main.py
  crate/operator/scale.py
  crate/operator/utils/kubeapi.py
  tests/test_bootstrap.py
  tests/test_create.py
  tests/test_kubeapi.py
  tests/test_webhooks.py
Labels: ready-to-merge

#121 Implement @kopf.on.resume handler
  CHANGES.rst
  crate/operator/constants.py
  crate/operator/main.py
  tests/test_resume.py
Labels: ready-to-merge

#120 Update bootstrapping of users to add label to secrets
  CHANGES.rst
  crate/operator/bootstrap.py
  crate/operator/main.py
  crate/operator/utils/kubeapi.py
  tests/test_bootstrap.py
Labels: ready-to-merge

#125 Allow overriding node.attr.zone
  CHANGES.rst
  crate/operator/create.py
  docs/source/configuration.rst
  tests/test_create.py
Labels: ready-to-merge

#129 Use intersphinx links for links to the CrateDB docs
  docs/source/concepts.rst
Labels: ready-to-merge

#126 Watch on Kubernetes Secrets and update user passwords if needed
  CHANGES.rst
  crate/operator/cratedb.py
  crate/operator/main.py
  crate/operator/update_user_password.py
  docs/source/concepts.rst
  tests/test_update_password.py
Labels: enhancement, ready-to-merge

#132 Wait a bit longer in user password tests
  tests/test_update_password.py
Labels: ready-to-merge

#133 Update permissions of the service account to be able to watch secrets
  deploy/rbac.yaml
Labels: ready-to-merge
